# Generated by Django 3.0.2 on 2020-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie_genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='movie_action',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='movie_adventure',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='movie_animation',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='movie_horror',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_youtube_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
