# Generated by Django 3.0.2 on 2020-03-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200303_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_adventure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_animation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_horror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
