# Generated by Django 3.0.2 on 2020-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200309_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_rating',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
